// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJS2liZZ56FIPLC-h-lqS92dmTVv36ry8',
    appId: '1:431959839068:web:87d482bcbb26ee63783199',
    messagingSenderId: '431959839068',
    projectId: 'social-media-4f06a',
    authDomain: 'social-media-4f06a.firebaseapp.com',
    storageBucket: 'social-media-4f06a.appspot.com',
    measurementId: 'G-WRMQWENCKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6aK7JcICUJjjmHujI26DUCLOyEOw1IAk',
    appId: '1:431959839068:android:db679f37f346edd5783199',
    messagingSenderId: '431959839068',
    projectId: 'social-media-4f06a',
    storageBucket: 'social-media-4f06a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzbnOYzXzz2YJPnwRH8zoA4xD9Stq_21Y',
    appId: '1:431959839068:ios:8f35d765331b9b29783199',
    messagingSenderId: '431959839068',
    projectId: 'social-media-4f06a',
    storageBucket: 'social-media-4f06a.appspot.com',
    androidClientId: '431959839068-3onqpmuou33sbnl9418g0a1dlqdsgfku.apps.googleusercontent.com',
    iosClientId: '431959839068-tiuar60i9tvmb7b29qdahhj5d5rk8iqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzbnOYzXzz2YJPnwRH8zoA4xD9Stq_21Y',
    appId: '1:431959839068:ios:8f35d765331b9b29783199',
    messagingSenderId: '431959839068',
    projectId: 'social-media-4f06a',
    storageBucket: 'social-media-4f06a.appspot.com',
    androidClientId: '431959839068-3onqpmuou33sbnl9418g0a1dlqdsgfku.apps.googleusercontent.com',
    iosClientId: '431959839068-tiuar60i9tvmb7b29qdahhj5d5rk8iqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentCourse',
  );
}
